export const Datas = [
    {
        id: 1,
        category: 'education',
        icon: 'icon-graduation',
        year: '2018 - 2021',
        title: 'SMPIT Fathan Mubina',
        desc: 'Education at SMPIT Fathan Mubina Islamic Boarding School developed the character of discipline, responsibility, and social skills, even though I have no direct technical experience in the IT field.',
    },
    {
        id: 2,
        category: 'education',
        icon: 'icon-graduation',
        year: '2018 - 2021',
        title: 'SMK Wikrama Bogor',
        desc: 'The Software and Game Engineering Department at SMK Wikrama Bogor provides website and application development skills, as well as practical experience in frontend and backend technologies.',
    },
    {
        id: 3,
        category: 'education',
        icon: 'icon-graduation',
        year: 'August - December 2024',
        title: 'Global Gengou Gakko',
        desc: 'The intensive Japanese course at Global Gengou Gakko improved my Japanese language skills to N4 level, covering grammar, vocabulary, and speaking and writing skills.',
    },
    {
        id: 4,
        category: 'experience',
        icon: 'icon-briefcase',
        year: 'July - December 2023',
        title: 'Frontend Web Developer Intern',
        desc: 'As a Frontend Intern at PT Kreasi Sawala Nusantara, I develop and optimize the appearance and user experience of websites using HTML, CSS, and JavaScript.',
    },
    {
        id: 5,
        category: 'experience',
        icon: 'icon-briefcase',
        year: 'May 2024',
        title: 'Competence Test',
        desc: "Taking the Competency Test by creating a website using Laravel as an evaluation of the eligibility of graduating from SMK. This process involves designing, developing, and completing projects according to industry standards."
    },
    {
        id: 6,
        category: 'experience',
        icon: 'icon-briefcase',
        year: 'March 2024 - Present',
        title: 'Freelance',
        desc: 'As a freelance web developer, I work on website development projects with a focus on responsive design and optimal user experience, as well as communicating directly with clients.',
    },
];
